### PR TITLE
Canonical Ltd is replaced with Canonical & Use Go Modules

### PR DESCRIPTION
**Pull request by bugraaydogar**
- Use go modules instead of govendor
- Change paths to canonical instead of CanonicalLtd

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
Looks good, but why `docs/IoTManagement.svg` is changed?

**Comment by bugraaydogar** [comment]
> Looks good, but why `docs/IoTManagement.svg` is changed?

There is a link inside svg which was redirecting to old repository.

**Comment by alfonsosanchezbeato** [comment]
> > Looks good, but why `docs/IoTManagement.svg` is changed?
> 
> There is a link inside svg which was redirecting to old repository when user clicks to the picture.

I see, nice catch!

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM

**Pull request merged**
